import pytest
from bofhound.ad.models.bloodhound_computer import BloodHoundComputer
from bofhound.ad.models.bloodhound_object import BloodHoundObject
from bloodhound.enumeration.acls import SecurityDescriptor, ACL, ACCESS_ALLOWED_ACE, ACCESS_MASK, ACE, ACCESS_ALLOWED_OBJECT_ACE, has_extended_right, EXTRIGHTS_GUID_MAPPING, can_write_property, ace_applies


@pytest.fixture
def parsed_partial_computer():
    pass


@pytest.fixture
def parsed_full_computer():
    yield {
        "objectclass": "top, person, organizationalPerson, user, computer",
        "cn": "WIN10",
        "distinguishedname": "CN=WIN10,OU=Workstations,DC=windomain,DC=local",
        "instancetype": "4",
        "whencreated": "20220112013543.0Z",
        "whenchanged": "20220401134507.0Z",
        "usncreated": "14202",
        "usnchanged": "24046",
        "ntsecuritydescriptor": "AQAEjJgJAAC0CQAAAAAAABQAAAAEAIQJMQAAAAUASAAgAAAAAwAAABAgIF+ledARkCAAwE/C1M+Gepa/5g3QEaKFAKoAMEniAQUAAAAAAAUVAAAANowB26uPcGmReUlF6AMAAAUASAAgAAAAAwAAAFB5lr/mDdARooUAqgAwSeKGepa/5g3QEaKFAKoAMEniAQUAAAAAAAUVAAAANowB26uPcGmReUlF6AMAAAUASAAgAAAAAwAAAFN5lr/mDdARooUAqgAwSeKGepa/5g3QEaKFAKoAMEniAQUAAAAAAAUVAAAANowB26uPcGmReUlF6AMAAAUASAAgAAAAAwAAANC/Cj5qEtARoGAAqgBsM+2Gepa/5g3QEaKFAKoAMEniAQUAAAAAAAUVAAAANowB26uPcGmReUlF6AMAAAUAOAAIAAAAAQAAAEeV43IYe9ERre8AwE/Y1c0BBQAAAAAABRUAAAA2jAHbq49waZF5SUXoAwAABQA4AAgAAAABAAAAiEem8wZT0RGpxQAA+ANnwQEFAAAAAAAFFQAAADaMAdurj3BpkXlJRegDAAAFADgAIAAAAAEAAAAAQhZMwCDQEadoAKoAbgUpAQUAAAAAAAUVAAAANowB26uPcGmReUlF6AMAAAUAOAAwAAAAAQAAAH96lr/mDdARooUAqgAwSeIBBQAAAAAABRUAAAA2jAHbq49waZF5SUUFAgAABQAsAAMAAAABAAAAqHqWv+YN0BGihQCqADBJ4gECAAAAAAAFIAAAACYCAAAFACwAEAAAAAEAAAAdsalGrmBaQLfo/4pY1FbSAQIAAAAAAAUgAAAAMAIAAAUAKAAAAQAAAQAAAFMacqsvHtARmBkAqgBAUpsBAQAAAAAAAQAAAAAFACgACAAAAAEAAABHleNyGHvREa3vAMBP2NXNAQEAAAAAAAUKAAAABQAoAAgAAAABAAAAiEem8wZT0RGpxQAA+ANnwQEBAAAAAAAFCgAAAAUAKAAwAAAAAQAAAIa4tXdKlNERrr0AAPgDZ8EBAQAAAAAABQoAAAAAACQA1AEDAAEFAAAAAAAFFQAAADaMAdurj3BpkXlJRegDAAAAACQA/wEPAAEFAAAAAAAFFQAAADaMAdurj3BpkXlJRQACAAAAABgA/wEPAAECAAAAAAAFIAAAACQCAAAAABQAAwAAAAEBAAAAAAAFCgAAAAAAFACUAAIAAQEAAAAAAAULAAAAAAAUAP8BDwABAQAAAAAABRIAAAAFEjgAIAAAAAMAAABbspQaIAi6R53LgK7637NwhnqWv+YN0BGihQCqADBJ4gEBAAAAAAAFCgAAAAUSOAAwAAAAAwAAAGL91v7f+9lBsl8a2z53q3eGepa/5g3QEaKFAKoAMEniAQEAAAAAAAUKAAAABRo8ABAAAAADAAAAAEIWTMAg0BGnaACqAG4FKRTMKEg3FLxFmwetbwFeXygBAgAAAAAABSAAAAAqAgAABRo8ABAAAAADAAAAAEIWTMAg0BGnaACqAG4FKbp6lr/mDdARooUAqgAwSeIBAgAAAAAABSAAAAAqAgAABRo8ABAAAAADAAAAECAgX6V50BGQIADAT8LUzxTMKEg3FLxFmwetbwFeXygBAgAAAAAABSAAAAAqAgAABRo8ABAAAAADAAAAECAgX6V50BGQIADAT8LUz7p6lr/mDdARooUAqgAwSeIBAgAAAAAABSAAAAAqAgAABRo8ABAAAAADAAAAQMIKvKl50BGQIADAT8LUzxTMKEg3FLxFmwetbwFeXygBAgAAAAAABSAAAAAqAgAABRo8ABAAAAADAAAAQMIKvKl50BGQIADAT8LUz7p6lr/mDdARooUAqgAwSeIBAgAAAAAABSAAAAAqAgAABRo8ABAAAAADAAAAQi+6WaJ50BGQIADAT8LTzxTMKEg3FLxFmwetbwFeXygBAgAAAAAABSAAAAAqAgAABRo8ABAAAAADAAAAQi+6WaJ50BGQIADAT8LTz7p6lr/mDdARooUAqgAwSeIBAgAAAAAABSAAAAAqAgAABRo8ABAAAAADAAAA+IhwA+EK0hG0IgCgyWj5ORTMKEg3FLxFmwetbwFeXygBAgAAAAAABSAAAAAqAgAABRo8ABAAAAADAAAA+IhwA+EK0hG0IgCgyWj5Obp6lr/mDdARooUAqgAwSeIBAgAAAAAABSAAAAAqAgAABRI4ADAAAAABAAAAD9ZHW5BgskCfNypN6I8wYwEFAAAAAAAFFQAAADaMAdurj3BpkXlJRQ4CAAAFEjgAMAAAAAEAAAAP1kdbkGCyQJ83Kk3ojzBjAQUAAAAAAAUVAAAANowB26uPcGmReUlFDwIAAAUQOAAIAAAAAQAAAKZtAps8DVxGi+5RmdcWXLoBBQAAAAAABRUAAAA2jAHbq49waZF5SUXoAwAABRo4AAgAAAADAAAApm0CmzwNXEaL7lGZ1xZcuoZ6lr/mDdARooUAqgAwSeIBAQAAAAAAAwAAAAAFEjgACAAAAAMAAACmbQKbPA1cRovuUZnXFly6hnqWv+YN0BGihQCqADBJ4gEBAAAAAAAFCgAAAAUSOAAQAAAAAwAAAG2exrfHLNIRhU4AoMmD9giGepa/5g3QEaKFAKoAMEniAQEAAAAAAAUJAAAABRo4ABAAAAADAAAAbZ7Gt8cs0hGFTgCgyYP2CJx6lr/mDdARooUAqgAwSeIBAQAAAAAABQkAAAAFGjgAEAAAAAMAAABtnsa3xyzSEYVOAKDJg/YIunqWv+YN0BGihQCqADBJ4gEBAAAAAAAFCQAAAAUSOAAgAAAAAwAAAJN7G+pIXtVGvGxN9P2nijWGepa/5g3QEaKFAKoAMEniAQEAAAAAAAUKAAAABRosAJQAAgACAAAAFMwoSDcUvEWbB61vAV5fKAECAAAAAAAFIAAAACoCAAAFGiwAlAACAAIAAACcepa/5g3QEaKFAKoAMEniAQIAAAAAAAUgAAAAKgIAAAUaLACUAAIAAgAAALp6lr/mDdARooUAqgAwSeIBAgAAAAAABSAAAAAqAgAABRMoADAAAAABAAAA5cN4P5r3vUaguJ0YEW3ceQEBAAAAAAAFCgAAAAUSKAAwAQAAAQAAAN5H5pFv2XBLlVfWP/TzzNgBAQAAAAAABQoAAAAAEiQA/wEPAAEFAAAAAAAFFQAAADaMAdurj3BpkXlJRQcCAAAAEhgABAAAAAECAAAAAAAFIAAAACoCAAAAEhgAvQEPAAECAAAAAAAFIAAAACACAAABBQAAAAAABRUAAAA2jAHbq49waZF5SUXoAwAAAQUAAAAAAAUVAAAANowB26uPcGmReUlFAQIAAA==",
        "name": "WIN10",
        "objectguid": "f981e173-4db8-48f9-9c2d-3d4987698505",
        "useraccountcontrol": "4096",
        "badpwdcount": "0",
        "codepage": "0",
        "countrycode": "0",
        "badpasswordtime": "0",
        "lastlogoff": "0",
        "lastlogon": "132933148216284771",
        "localpolicyflags": "0",
        "pwdlastset": "132888464114765330",
        "primarygroupid": "515",
        "objectsid": "S-1-5-21-3674311734-1768984491-1162443153-1104",
        "accountexpires": "9223372036854775807",
        "logoncount": "222",
        "samaccountname": "WIN10$",
        "samaccounttype": "805306369",
        "operatingsystem": "Windows 10 Enterprise Evaluation",
        "operatingsystemversion": "10.0 (18363)",
        "dnshostname": "win10.windomain.local",
        "serviceprincipalname": "WSMAN/win10, WSMAN/win10.windomain.local, TERMSRV/WIN10, TERMSRV/win10.windomain.local, RestrictedKrbHost/WIN10, HOST/WIN10, RestrictedKrbHost/win10.windomain.local, HOST/win10.windomain.local",
        "objectcategory": "CN=Computer,CN=Schema,CN=Configuration,DC=windomain,DC=local",
        "iscriticalsystemobject": "FALSE",
        "dscorepropagationdata": "20220325174020.0Z, 16010101000001.0Z",
        "lastlogontimestamp": "132932943074365707",
        "msds-supportedencryptiontypes": "28",
        "ms-mcs-admpwd": "testpassword",
        "ms-mcs-admpwdexpirationtime": "132953152469914742"
    }


def test_constructor_hasLaps(parsed_full_computer):
    bhc = BloodHoundComputer(parsed_full_computer)

    assert bhc.Properties['haslaps'] == True
    assert bhc.Properties['operatingsystem'] == 'Windows 10 Enterprise Evaluation'